// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC3LdsKw2AH9EKq2f49eLCdf-jj-JWmkY',
    appId: '1:941151806887:web:993ab6d91b5511e8fb8282',
    messagingSenderId: '941151806887',
    projectId: 'lumadlingua',
    authDomain: 'lumadlingua.firebaseapp.com',
    storageBucket: 'lumadlingua.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNKBx20FxwqjZ4d2J0ghBiwpSgiDtUuZM',
    appId: '1:941151806887:android:6c4a37937ae32e76fb8282',
    messagingSenderId: '941151806887',
    projectId: 'lumadlingua',
    storageBucket: 'lumadlingua.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzkykzQRIkP5L8i_ZOZVrIYbcXFRWwL7k',
    appId: '1:941151806887:ios:1d749c9a2fb11b30fb8282',
    messagingSenderId: '941151806887',
    projectId: 'lumadlingua',
    storageBucket: 'lumadlingua.firebasestorage.app',
    iosBundleId: 'com.example.lumadLingua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzkykzQRIkP5L8i_ZOZVrIYbcXFRWwL7k',
    appId: '1:941151806887:ios:1d749c9a2fb11b30fb8282',
    messagingSenderId: '941151806887',
    projectId: 'lumadlingua',
    storageBucket: 'lumadlingua.firebasestorage.app',
    iosBundleId: 'com.example.lumadLingua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC3LdsKw2AH9EKq2f49eLCdf-jj-JWmkY',
    appId: '1:941151806887:web:48de1b5050db0807fb8282',
    messagingSenderId: '941151806887',
    projectId: 'lumadlingua',
    authDomain: 'lumadlingua.firebaseapp.com',
    storageBucket: 'lumadlingua.firebasestorage.app',
  );
}



