import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/user_preferences_provider.dart';

class AppLocalization {
  final String languageCode;

  AppLocalization(this.languageCode);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // 1. Onboarding & Auth
      'app_name': 'Lumad Lingua',
      'step': 'Step',
      'identity': 'Identity',
      'roots': 'Roots',
      'path': 'Path',
      'ritual': 'Ritual',
      'welcome_guest': 'Welcome, Honored Guest!',
      'invited_as': "You've been invited as a",
      'for': 'for',
      'already_have_account': 'Already have an account?',
      'dont_have_account': "Don't have an account?",
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'signing_in': 'Signing In...',
      'waiting': 'Waiting...',
      'continue': 'Continue',
      'next_ritual': 'Next: The Ritual',
      'back': 'Back',
      'or': 'OR',
      'sign_in_google': 'Sign in with Google',
      'quick_join_google': 'Quick Join with Google',
      'email_address': 'Email Address',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'display_name': 'Display Name',
      'province': 'Province',
      'municipality': 'Municipality',
      'select_province': 'Select Province',
      'select_municipality': 'Select Municipality',
      'village_code_optional': 'Village Code (Optional)',
      'village_code_hint': 'Enter a code from your educator to join their specific community village.',
      'fill_all_fields': 'Please fill all fields correctly',
      'complete_fields_terms': 'Please complete all fields and accept the Terms',
      'native_language': 'Native Language',
      'select_native_language': 'Select Native Language',
      'valid_email': 'Sacred name (email) must be valid',
      'password_length': 'Ancient chant (password) must be at least 6 notes',
      'passwords_dont_match': 'The chants do not match',
      'tribe_name_length': 'Tribe name must be at least 3 characters',
      'invalid_email_format': 'Invalid email format',
      'password_strength': 'Password Strength',
      'password_strength_weak': 'Weak',
      'password_strength_fair': 'Fair',
      'password_strength_strong': 'Strong',
      'req_min_8_chars': 'At least 8 characters',
      'req_uppercase': 'Uppercase letter (A-Z)',
      'req_lowercase': 'Lowercase letter (a-z)',
      'req_number': 'Number (0-9)',
      'req_special_char': 'Special character',
      'password_not_strong': 'Password does not meet strength requirements',
      'verify_your_email': 'Verify Your Email',
      'verification_instructions': 'We have sent a verification link to your email address. Please check your inbox or spam folder and click the link to verify.',
      'verification_email_sent': 'Verification email sent! Please check your inbox and spam folder.',
      'ive_verified': "I've Verified My Email",
      'checking': 'Checking...',
      'resend_verification_email': 'Resend Verification Email',
      'resend_in_seconds': 'Resend in {seconds}s',
      'email_verified_success': 'Email verified successfully!',
      'email_not_verified_yet': 'Email is not verified yet. Please check your email and click the verification link.',
      'sign_out_or_change_account': 'Sign Out / Change Account',
      'back_to_sign_in': 'Back to Sign In',
      'check_email_instructions': 'Please check your inbox and spam folder for instructions to reset your password.',
      'password_too_short': 'Password too short',
      'forgot_password': 'Forgot Password?',
      'reset_password_title': 'Reset Password',
      'reset_password_desc': 'Enter your registered email address and we will send you a link to reset your password.',
      'send_reset_link': 'Send Reset Link',
      'cancel': 'Cancel',
      'reset_email_sent': 'Password reset link has been sent to your email.',
      'error_user_not_found': 'No account found with this email address.',
      'error_wrong_password': 'Incorrect password. Please try again.',
      'error_invalid_credential': 'Invalid email or password. Please check your credentials.',
      'error_email_already_in_use': 'An account already exists with this email address.',
      'error_invalid_email': 'Please enter a valid email address.',
      'error_user_disabled': 'This account has been disabled. Please contact support.',
      'error_too_many_requests': 'Too many failed attempts. Please try again later.',
      'error_network_failed': 'Network connection failed. Please check your internet connection.',
      'error_weak_password': 'Password is too weak. Please choose a stronger password.',
      'error_operation_not_allowed': 'This sign-in method is currently disabled.',
      'error_auth_generic': 'Authentication failed. Please try again.',
      'connection_lumad': 'What is your connection to the Lumad languages?',
      'heritage_learner': 'I am a heritage learner (it is my family language)',
      'l2_learner': 'I am an L2 learner (learning it as a second language)',
      'researcher_educator': 'I am a researcher or educator',
      'curious_culture': 'I am just curious about the culture',
      'exposure_question': 'How often do you hear or speak your ancestral language?',
      'daily': 'Daily',
      'occasionally': 'Occasionally',
      'rarely': 'Rarely',
      'never': 'Never',
      'goal_question': 'What is your main goal for using this app?',
      'fluent_goal': 'To become fluent',
      'elders_goal': 'To understand my elders better',
      'preserve_goal': 'To preserve the language for the next generation',
      'assessment_goal': 'To pass an assessment',
      'learning_goal': 'Learning Goal',
      'culture': 'Culture',
      'travel': 'Travel',
      'ancestry': 'Ancestry',
      'community': 'Community',
      'research': 'Research',
      'agree_to': 'I agree to the',
      'terms': 'Terms',
      'and': 'and',
      'privacy_policy': 'Privacy Policy',
      'terms_conditions': 'Terms & Conditions',
      'close': 'CLOSE',
      'legal_mansaka': 'By using Lumad Lingua, you agree to respect the cultural heritage of the Mansaka and other Lumad tribes. Users are prohibited from misusing, misrepresenting, or commercializing traditional knowledge without proper tribal consent...',
      'legal_privacy': 'We value your privacy. Your data (name, email, and location) is used solely to enhance your learning experience and track your progress. We do not sell your personal information to third parties...',

      // 2. User Profiles
      'tribe_member': 'Tribe Member',
      'tribe_member_caps': 'TRIBE MEMBER',
      'system_overseer': 'SYSTEM OVERSEER',
      'researcher_staff': 'RESEARCHER STAFF',
      'wisdom_guide': 'WISDOM GUIDE',
      'elder_pathfinder': 'ELDER PATHFINDER',
      'philippines': 'PHILIPPINES',
      'unknown': 'Unknown',
      'total_xp': 'TOTAL XP',
      'day_streak': 'DAY STREAK',
      'words': 'WORDS',
      'vitality': 'VITALITY',
      'monitor': 'MONITOR',
      'students': 'STUDENTS',
      'accuracy': 'ACCURACY',
      'rating': 'RATING',
      'rank': 'RANK',
      'novice': 'NOVICE',
      'guardian': 'GUARDIAN',
      'elder': 'ELDER',
      'elite': 'ELITE',
      'na': 'N/A',
      'journey_management': 'Journey Management',
      'edit_profile': 'Edit Profile',
      'update_location_bio': 'Update your location and bio',
      'wisdom_progression': 'Wisdom Progression',
      'wisdom_requirements': 'View requirements for your next rank and titles',
      'notification_sanctuary': 'Notification Sanctuary',
      'notification_desc': 'Manage alerts for daily goals and community messages',
      'data_privacy': 'Data & Privacy',
      'data_privacy_desc': 'Export your contributions or manage account security',
      'offline_wisdom': 'Offline Wisdom',
      'offline_wisdom_desc': 'Manage cached lessons and audio files for offline use',
      'light_sanctuary': 'Light Sanctuary',
      'dark_forest': 'Dark Forest',
      'switch_themes': 'Switch between light and dark themes',
      'join_village': 'Join a Village',
      'join_village_desc': 'Enter a code to connect with your local educator',
      'welcome_village': 'Welcome to the village! 🌿',
      'send_feedback': 'Send Feedback',
      'feedback_desc': 'Message your educators about your journey',
      'simulation_mode': 'Simulation Mode',
      'exit_simulation': 'Exit Simulation',
      'admin_overview': 'Return to Admin Overview',
      'test_content_desc': 'Switch to Learner view to test content',
      'log_out': 'LOG OUT',
      'choose_totem': 'Choose Ancestral Totem',
      'upload_picture': 'Upload New Picture',
      'remove_picture': 'Remove Picture',
      'pic_removed': 'Profile picture removed.',
      'uploading_totem': 'Uploading ancestral totem...',
      'pic_updated': 'Profile picture updated!',
      'upload_failed': 'Upload failed:',
      'choose_your_totem': 'Choose Your Ancestral Totem',
      'failed_update': 'Failed to update:',
      'join_comm_village': 'Join a community village',
      'village_code_entry': 'Enter the 6-character code provided by your educator to join their community.',
      'code': 'CODE',
      'join': 'JOIN',
      'village_code_label': 'VILLAGE CODE:',
      'activate_village': 'ACTIVATE VILLAGE CODE',
      'village_activated': 'Village activated! Students can now join your tribe. 🌿',
      'activation_failed': 'Activation failed:',
      'edit_sacred_profile': 'Edit Sacred Profile',
      'tribe_name': 'Tribe Name',
      'location': 'Location',
      'location_locked': 'Location is locked',
      'bio': 'Statement/Bio',
      'bio_hint': 'Teaching philosophy or heritage goals...',
      'save': 'SAVE',
      'feedback_prompt': 'Have a question or suggestion? Message your educators directly.',
      'type_message': 'Type your message...',
      'feedback_sent': 'Feedback sent to educators!',
      'send': 'SEND',
      'earned_artifacts': 'Earned Artifacts',
      'no_treasures': 'No Treasures',
      'no_artifacts_desc': 'No artifacts discovered by this member yet.',
      'error_artifacts': 'Error loading artifacts',

      // 3. Gamified Sessions
      'top_3': "YOU'RE IN THE TOP 3! 🔥",
      'elders_wisdom': "ELDERS' WISDOM",
      'correct': 'Correct!',
      'slipped': 'Slipped!',
      'sudden_death_survived': 'SUDDEN DEATH SURVIVED! +1 Heart',
      'spirit_exhausted': 'SPIRIT EXHAUSTED',
      'strength_faded': "Your strength has faded before the ritual's end. But remember what the elders say:",
      'sacred_revival': 'SACRED REVIVAL (50 ✨)',
      'review_slipped': 'REVIEW SLIPPED TERMS',
      'return_village': 'RETURN TO VILLAGE',
      'slipped_terms': 'SLIPPED TERMS',
      'reflect_before_return': 'Reflect on these before returning.',
      'got_it': 'GOT IT',
      'badge_unlocked': 'Badge Unlocked!',
      'perfect_scholar_desc': 'You earned the Perfect Scholar badge for your flawless performance!',
      'awesome': 'Awesome!',
      'loot_drop': 'Loot Drop!',
      'add_vault': 'Add to Vault',
      'quote_1': 'Even the strongest tree bends in the storm to grow stronger.',
      'quote_2': 'A journey of a thousand miles has many rest stops.',
      'quote_3': 'Wisdom is not built in a day, but in the lessons of the fall.',
      'quote_4': 'The spirit is resilient, like the bamboo after the wind.',
      'quote_5': 'To learn is to fall and rise again, each time with more grace.',
      'leave_session': 'Leave Session?',
      'leave_session_desc': 'Your progress in this session will be lost. Are you sure you want to quit?',
      'keep_going': 'Keep Going',
      'quit': 'Quit',
      'out_of_hearts': 'Out of Hearts! 💔',
      'restore_strength': 'Your journey has grown difficult. Would you like to restore your strength?',
      'cost': 'Cost:',
      'not_enough_crystals': 'Not enough crystals!',
      'end_session': 'End Session',
      'restore_hearts': 'Restore Hearts',
      'confidence_question': 'How confident do you feel about the words you just learned?',
      'very_confident': 'Very confident',
      'somewhat_confident': 'Somewhat confident',
      'bit_confused': 'A bit confused',
      'need_practice': 'I need more practice',
      'difficulty_question': 'Was the difficulty of this lesson appropriate?',
      'too_easy': 'Too easy',
      'just_right': 'Just right',
      'too_hard': 'Too hard',
      'very_challenging': 'Very challenging',
      'utility_question': 'How likely are you to use these words in a conversation?',
      'very_likely': 'Very likely',
      'possibly': 'Possibly',
      'not_sure': 'Not sure',
      'unlikely': 'Unlikely',

      // 4. Security
      'account_security': 'ACCOUNT SECURITY',
      'account_protected': 'Account Protected',
      'data_encryption_desc': 'Your sacred data is encrypted with village protocols.',
      'update_password': 'UPDATE PASSWORD',
      'data_management': 'DATA MANAGEMENT',
      'export_data': 'Export My Data',
      'export_data_desc': 'Copy a JSON version of your contributions and activity',
      'data_exported': 'Data exported and copied to clipboard!',
      'export_failed': 'Export failed:',
      'activity_logs': 'Activity Logs',
      'review_security': 'Review your recent sign-in and security activity',
      'prepared_by_elders': 'is being prepared by the village elders.',
      'privacy_controls': 'PRIVACY CONTROLS',
      'public_profile': 'Public Profile',
      'public_profile_desc': 'Allow other tribe members to see your achievements and rank',
      'usage_analytics': 'Usage Analytics',
      'share_anonymous_desc': 'Share anonymous data to help improve the platform',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'incorrect_current_pass': 'Incorrect current password.',
      'password_updated': 'Password updated successfully!',
      'danger_zone': 'DANGER ZONE',
      'delete_account_desc': 'Permanently delete your account and all associated ancestral contributions.',
      'delete_account_btn': 'DELETE ACCOUNT',
      'sacrifice_account': 'Sacrifice Account?',
      'irreversible_desc': 'This action is irreversible. All your progress, XP, and contributions will be lost. Please enter your password to confirm.',
      'incorrect_pass': 'Incorrect password.',
      'deletion_failed': 'Deletion failed:',
      'delete': 'DELETE',

      // 5. Multi-Player
      'ancestral_guardian': 'Ancestral Guardian',
      'lingua_duel': 'LINGUA DUEL',
      'duel_desc': 'Challenge ancestral guardians or live learners to ritual combat. Answer quickly to defend your energy and claim ancient crystal rewards.',
      'enter_arena': 'ENTER ARENA',
      'retreat': 'RETREAT',
      'seeking_opponent': 'SEEKING OPPONENT...',
      'stirring_spirits': 'Stirring the spirits of the arena...',
      'match_found': 'MATCH FOUND!',
      'prepare_combat': 'Prepare your mind for ritual combat.',
      'you_label': 'YOU',
      'victory': 'VICTORY!',
      'defeat': 'DEFEAT',
      'victory_reward': '+150 XP  \u2022  +25 Mist Crystals',
      'defeat_desc': 'Try again to calibrate your knowledge sparks.',
      'leave_arena': 'LEAVE ARENA',
      'duel_question_prefix': 'What does "{word}" mean?',
      'duel_question_gm': 'How do you say Good Morning in Mansaka?',
      'duel_question_land': 'What is the Mansaka word for Land?',

      // 6. Scenario Hub & Stories
      'scenario_stories': 'Scenario Stories',
      'mastered': 'MASTERED',
      'choose_path_desc': 'Choose your path. Every word matters.',
      'search_stories': 'Search stories...',
      'replay_story': 'REPLAY STORY',
      'start_scenario': 'START SCENARIO',

      // 7. Wisdom Sanctuary / Dictionary
      'definition': 'DEFINITION',
      'usage_example': 'USAGE EXAMPLE',
      'example_usage': 'EXAMPLE USAGE',
      'translation': 'TRANSLATION',
      'daily_review': 'DAILY REVIEW',
      'mastery_level_up': 'Mastery Level Up!',
      'session_complete_msg': 'Session Complete!',
      'studied_all_cards': 'You studied all cards.',
      'search_dictionary': 'Search dictionary...',
      'search_cards': 'Search cards...',
      'saved_label': 'SAVED',
      'all_label': 'ALL',
      'no_saved_words': 'You haven\'t saved any words yet.',
      'no_search_results': 'No words match your search.',
      'sort_az': 'A - Z',
      'sort_za': 'Z - A',
      'sort_newest': 'Newest First',
      'sort_oldest': 'Oldest First',
      'share_label': 'SHARE',
      'save_label': 'SAVE',
      'saved_caps': 'SAVED',

      // 8. Leaderboard & Social
      'top_learners': 'TOP LEARNERS',
      'weekly_fame': 'WEEKLY HALL OF FAME',
      'global_spirits': 'GLOBAL SPIRITS',
      'salute_sent': 'Salute sent to {name}!',
      'salute_failed': 'Failed to send salute.',
      'incoming_kin_requests': 'INCOMING KINSHIP REQUESTS',
      'accept': 'Accept',
      'decline': 'Decline',
      'add_kin': 'Add Kin',
      'already_kin': 'Already Kin',
      'kin_request_sent': 'Request Sent',
      'no_kin_yet': 'No kin added yet. Tap Invite Kin to search and connect with members!',
      'no_members_found': 'No tribal members found.',
      'salute_button': 'Salute',
      'remove_kin': 'Remove Kin',
      'rank_label': 'Rank',
      'spirit_score': 'Spirit Score',
      'village_label': 'Village',

      // 9. Dashboards & Rituals
      'good_morning': 'Good Morning',
      'welcome_back': 'Welcome back',
      'daily_rituals': 'DAILY RITUALS',
      'attention_needed': 'Attention Needed',
      'village_challenge': 'VILLAGE CHALLENGE',
      'challenge_completed': "You have already completed today's challenge!",
      'home': 'HOME',
      'you': 'YOU',
      'learn': 'LEARN',
      'dashboard': 'DASHBOARD',
      'users': 'USERS',

      // 10. Admin & Educator Tools
      'stats_refreshed': 'Platform stats refreshed',
      'wotd_rotated': 'Word of the Day rotated',
      'confirm_wotd': 'Confirm WOTD',
      'approve_all': 'APPROVE ALL',
      'analytics_report': 'Educator Analytics Report',
      'system_overview': 'System Overview',
      'dialect_dist': 'Dialect Distribution',
      'add_word': 'Add Word',
      'add_blank': 'Add Blank Answer',
      'true_label': 'TRUE',
      'false_label': 'FALSE',
      'pedagogical_analytics': 'PEDAGOGICAL ANALYTICS',
      'learning_eco_health': 'LEARNING ECOSYSTEM HEALTH',
      'retention_rate': 'Retention Rate',
      'active_terms': 'Active Terms',
      'lesson_heatmaps': 'LESSON HEATMAPS (STUMBLE POINTS)',
      'student_stumbles_empty': 'The trail is fresh. No student stumbles recorded yet.',
      'srs_mastery_title': 'SPACED REPETITION (SRS) MASTERY',
      'mastery_box_dist': 'Mastery Box Distribution',
      'failed_sync_wisdom': 'Failed to sync wisdom: {error}',
      'retry_sync': 'RETRY SYNC',
      'ancestral_lesson_default': 'Ancestral Lesson',
      'box_label': 'BOX',
      'xp_growth_trends': 'USER XP GROWTH TRENDS (7 DAYS)',
      'pronunciation_by_dialect': 'PRONUNCIATION ACCURACY BY DIALECT',
      'pronunciation_by_location': 'PRONUNCIATION ACCURACY BY LOCATION',
      'aggregate_xp_growth': 'AGGREGATE XP GROWTH',
      'insufficient_voice_data': 'Insufficient voice data.',
      'no_xp_activity': 'No XP activity recorded.',

      // 11. Miscellaneous
      'no_audio': 'No audio available',
      'no_translation': 'No translation found.',
      'ancestral_gallery': 'Ancestral Gallery',
      'view_sacred_artifacts': 'View Sacred Artifacts',
      'saved_locally_sync': 'Saved locally. Will sync when online.',
      'offline_synced': 'Offline drafts synced successfully!',

      // 12. Achievements
      'ancestral_honors': 'Ancestral Honors',
      'your_legacy': 'Your Legacy',
      'legacy_desc': 'Tracing your journey through ancestral wisdom.',
      'collected': 'Collected',
      'total_label': 'Total',
      'vault_locked': 'Vault Locked',
      'unlock_treasures': 'Complete lessons to unlock cultural treasures.',

      // 13. Warriors Circle
      'warriors_circle': 'WARRIORS CIRCLE',
      'search_members': 'Search members...',
      'invite_kin': 'INVITE KIN',
      'warrior_label': 'WARRIOR',
      'duel_btn': 'DUEL',

      // 14. Community Feed
      'living_feed': 'LIVING FEED',
      'community_quiet': 'The community is quiet... for now. 🌿',
      'comments_label': 'Comments',
      'conversation_soon': 'Conversation starting soon... 🌿',
      'add_comment_hint': 'Add a comment...',
      'sharing_update': 'Sharing update by {name}...',

      // 15. Ancestral Vault Shop
      'ancestral_vault_caps': 'ANCESTRAL VAULT',
      'vault_sealed': 'The vault is currently sealed.\nCheck back after your next ritual.',
      'ancestral_blessing': 'Ancestral blessing',
      'unlock_caps': 'UNLOCK',
      'not_enough_crystals_exchange': 'You require more Mist Crystals for this exchange.',
      'sacred_exchange': 'Sacred Exchange',
      'owned_caps': 'OWNED',
      'exchange_confirm': 'Do you wish to spend {cost} Mist Crystals to unlock the {item}?',
      'processing': 'Processing...',
      'legacy_unlocked': 'LEGACY UNLOCKED',
      'tap_return_vault': 'Tap to return to the vault',



      // 17. Streak History
      'streak_journey': 'STREAK JOURNEY',
      'on_fire': "You're on fire!",
      'start_journey_today': 'Start your journey today!',
      'streak_desc': 'Keep learning daily to grow your streak.',
      'streak_shields': 'STREAK SHIELDS',
      'available': 'Available',
      'get_more': 'GET MORE',
      'activity_map': 'ACTIVITY MAP',
      'milestones_caps': 'MILESTONES',
      'one_week': 'One Week',
      'month_wisdom': 'Month of Wisdom',
      'tribe_guardian_milestone': 'Tribe Guardian',
      'claim_caps': 'CLAIM',
      'claimed_msg': 'Claimed {reward}! 🎉',
      'crystals_reward': '{count} Crystals',

      // 18. Artifact Detail
      'lore_legend': 'Lore & Legend',
      'origin_craft': 'Origin & Craft',
      'share_heritage': 'SHARE HERITAGE',
      'sharing_lineage': 'Sharing lineage story...',
      'no_legend_yet': 'No legend yet. Uncover more rituals to reveal the full story of this sacred object.',

      // 19. Admin Overview
      'village_pulse': 'VILLAGE PULSE',
      'platform_stats': 'PLATFORM STATS',
      'total_users': 'Total Users',
      'words_added': 'Words Added',
      'audio_clips': 'Audio Clips',
      'manage_label': 'MANAGE',
      'dictionary_label': 'Dictionary',
      'lessons_label': 'Lessons',
      'advanced_analytics': 'ADVANCED PEDAGOGICAL ANALYTICS',
      'system_health_label': 'SYSTEM HEALTH',
      'user_growth_label': 'USER GROWTH (last 7 days)',
      'gamification_economics': 'GAMIFICATION & ECONOMICS',
      'warrior_circle_ops': 'WARRIOR CIRCLE OPS',
      'manage_seasons_desc': 'Manage seasons, shop prices, and duel moderation.',
      'go_economics_hub': 'GO TO ECONOMICS HUB',
      'force_rotation': 'FORCE ROTATION',
      'resume_auto': 'RESUME AUTO',
      'pick_manually': 'PICK MANUALLY',
      'good_morning_name': 'Maayong\nAdlaw,\n{name}!',
      'select_language': 'Select Language',
      'english': 'English',
      'filipino': 'Filipino',
      'bisaya': 'Bisaya',

      // 20. System Guide
      'system_nav_guide': 'SYSTEM NAVIGATION GUIDE',
      'welcome_lumad_lingua': 'Welcome to Lumad Lingua',
      'guide_title_1': '1. Cultural Heritage Orientation',
      'guide_desc_1': 'An overview of our specific indigenous community (e.g., Mansaka), explaining the vital importance of preserving our sacred ancestral dialects, oral literature, and ancient traditions.',
      'guide_title_2': '2. Learning Path Roadmap',
      'guide_desc_2': 'Walkthrough of the interactive step-by-step progress loop. Advance through structured tribal units, visit localized scenario hubs, and complete specialized vocabulary challenges.',
      'guide_title_3': '3. Pronunciation & Audio Guidelines',
      'guide_desc_3': 'Learn how to utilize the microphone for live pronunciation analysis. Listen carefully to accurate accent references and mimic elder pronunciations to calibrate your voice scores.',
      'guide_title_4': '4. Dictionary & Archive Navigation',
      'guide_desc_4': 'Effortlessly search through our deep indigenous word vaults. Explore comprehensive usage contexts, examples, and instant translations into English or Filipino.',
      'guide_title_5': '5. Community Peak & Engagement',
      'guide_desc_5': 'Understand the XP reward cycle, tribal progression ranks, and unique merit badges. Challenge peers in ritual duels and tap the spark icon to send a "Tribal Salute" to fellow learners.',
      'guide_title_6': '6. Data Privacy & Verification Transparency',
      'guide_desc_6': 'Total clarity on community custodianship. Discover how native terms, audio tips, and submitted records are protected, filtered, and officially verified by our tribal council and elders.',

      // 21. Onboarding Narrative
      'onboarding_title_1': 'The Echoes Fade',
      'onboarding_sub_1': 'OUR ANCESTRAL VOICES',
      'onboarding_desc_1': 'The sacred languages of our tribes are fading like mist at dawn. You have been chosen to gather the remaining echoes.',
      'onboarding_title_2': 'The Ancestral Vault',
      'onboarding_sub_2': 'SACRED KNOWLEDGE',
      'onboarding_desc_2': 'Every word you learn restores a piece of our history. Unlock ancient artifacts and rebuild the legacy of our people.',
      'onboarding_title_3': 'Your Tribal Journey',
      'onboarding_sub_3': 'WISDOM AWAITS',
      'onboarding_desc_3': 'Join the Warriors\' Circle and compete in ritual duels. The path to mastery is long, but the elders walk with you.',
      'begin_ritual': 'BEGIN THE RITUAL',
      'reset_in': 'RESET IN {time}',
      'challenge_hub': 'CHALLENGE HUB',
      'current_lesson': 'CURRENT LESSON',
      'lesson_progress': 'Lesson Progress',
      'review_ascent': 'REVIEW ASCENT',
      'continue_ascent': 'CONTINUE ASCENT',
      'start_your_journey': 'Start Your Journey',
      'begin_ascent_desc': 'Begin your ascent into the highlands and discover the Lumad heritage.',
      'start_unit_1': 'START UNIT 1',
      'botanical_archivists': 'The season\'s most active botanical archivists.',
      'view_all': 'VIEW ALL',
      'quiet_mountains': 'Quiet Mountains',
      'no_climbers': 'No climbers yet! Be the first to start the ascent.',
      'archive_xp': 'ARCHIVE XP',
      'keep_flame_alive': 'Keep the flame alive!',
      'ritual_empty_desc': 'No rituals today. Check back soon for more tribal challenges!',

      // 22. Offline & Sync
      'saved_offline_desc': 'Saved offline. We will sync your progress once you are back online.',
      'sync_conflicts': 'Sync Conflicts',
      'conflicts_desc': 'You have {count} lesson progress conflicts that need attention.',
      'resolve_now': 'RESOLVE NOW',
      'resolve_conflicts': 'Resolve Conflicts',
      'conflict_detected_desc': 'We found different progress data on this device and in the cloud. Which one would you like to keep?',
      'local_device': 'LOCAL DEVICE',
      'cloud_server': 'CLOUD SERVER',
      'keep_cloud': 'KEEP CLOUD',
      'use_local': 'USE LOCAL',
      'done': 'DONE',
    },
    'tl': {
      // 1. Onboarding & Auth
      'app_name': 'Lumad Lingua',
      'step': 'Hakbang',
      'identity': 'Pagkakakilanlan',
      'roots': 'Mga Ugat',
      'path': 'Landas',
      'ritual': 'Ritwal',
      'welcome_guest': 'Maligayang pagdating, Mahal na Panauhin!',
      'invited_as': 'Inimbitahan ka bilang',
      'for': 'para sa',
      'already_have_account': 'May account ka na?',
      'dont_have_account': 'Wala ka pang account?',
      'sign_in': 'Mag-sign In',
      'sign_up': 'Mag-sign Up',
      'signing_in': 'Nag-sign in...',
      'waiting': 'Naghihintay...',
      'continue': 'Magpatuloy',
      'next_ritual': 'Susunod: Ritwal',
      'back': 'Bumalik',
      'or': 'O',
      'sign_in_google': 'Mag-sign in gamit ang Google',
      'quick_join_google': 'Mabilis na Sumali gamit ang Google',
      'email_address': 'Email Address',
      'password': 'Password',
      'confirm_password': 'Kumpirmahin ang Password',
      'display_name': 'Pangalan na Ipapakita',
      'province': 'Probinsya',
      'municipality': 'Munisipalidad',
      'select_province': 'Pumili ng Probinsya',
      'select_municipality': 'Pumili ng Munisipalidad',
      'village_code_optional': 'Village Code (Opsyonal)',
      'village_code_hint': 'Ilagay ang code mula sa iyong educator para makasali sa kanilang community village.',
      'fill_all_fields': 'Pakipunan nang tama ang lahat ng field',
      'complete_fields_terms': 'Pakikumpleto ang lahat ng field at tanggapin ang Terms',
      'native_language': 'Katutubong Wika',
      'select_native_language': 'Pumili ng Katutubong Wika',
      'valid_email': 'Dapat valid ang email',
      'password_length': 'Dapat hindi bababa sa 6 na character ang password',
      'passwords_dont_match': 'Hindi magkatugma ang mga password',
      'tribe_name_length': 'Dapat hindi bababa sa 3 character ang pangalan ng tribe',
      'invalid_email_format': 'Hindi valid ang format ng email',
      'password_strength': 'Lakas ng Password',
      'password_strength_weak': 'Mahina',
      'password_strength_fair': 'Katamtaman',
      'password_strength_strong': 'Malakas',
      'req_min_8_chars': 'Hindi bababa sa 8 character',
      'req_uppercase': 'May malaking titik (A-Z)',
      'req_lowercase': 'May maliit na titik (a-z)',
      'req_number': 'May numero (0-9)',
      'req_special_char': 'May natatanging simbolo',
      'password_not_strong': 'Hindi naaabot ng password ang pamantayan sa lakas',
      'verify_your_email': 'I-verify ang Iyong Email',
      'verification_instructions': 'Nagpadala kami ng verification link sa iyong email address. Pakitingnan ang iyong inbox o spam folder at i-click ang link.',
      'verification_email_sent': 'Naipadala na ang verification email! Pakitingnan ang iyong inbox at spam folder.',
      'ive_verified': 'Na-verify Ko Na Ang Email Ko',
      'checking': 'Sinusuri...',
      'resend_verification_email': 'Ipadala Muli Ang Verification Email',
      'resend_in_seconds': 'Subukan muli sa {seconds}s',
      'email_verified_success': 'Matagumpay na na-verify ang email!',
      'email_not_verified_yet': 'Hindi pa na-verify ang email. Pakisuri ang iyong email at i-click ang link.',
      'sign_out_or_change_account': 'Mag-sign Out / Magpalit ng Account',
      'back_to_sign_in': 'Bumalik sa Sign In',
      'check_email_instructions': 'Pakitingnan ang iyong inbox at spam folder para sa mga tagubilin sa pag-reset ng password.',
      'password_too_short': 'Masyadong maikli ang password',
      'forgot_password': 'Nakalimutan ang Password?',
      'reset_password_title': 'I-reset ang Password',
      'reset_password_desc': 'Ilagay ang iyong rehistradong email at ipapadala namin ang link upang i-reset ang iyong password.',
      'send_reset_link': 'Ipadala ang Link',
      'cancel': 'Kanselahin',
      'reset_email_sent': 'Naipadala na sa iyong email ang link sa pag-reset ng password.',
      'error_user_not_found': 'Walang nahanap na account gamit ang email na ito.',
      'error_wrong_password': 'Maling password. Pakisubukan ulit.',
      'error_invalid_credential': 'Hindi valid ang email o password. Pakisuri ang iyong impormasyon.',
      'error_email_already_in_use': 'May umiiral nang account gamit ang email address na ito.',
      'error_invalid_email': 'Maglagay ng valid na email address.',
      'error_user_disabled': 'Na-disable ang account na ito. Makipag-ugnayan sa suporta.',
      'error_too_many_requests': 'Sobrang daming nabigong pagsubok. Pakisubukan ulit mamaya.',
      'error_network_failed': 'Nawalan ng koneksyon sa internet. Pakisuri ang iyong koneksyon.',
      'error_weak_password': 'Masyadong mahina ang password. Pumili ng mas matatag na password.',
      'error_operation_not_allowed': 'Kasalukuyang naka-disable ang paraan ng pag-sign in na ito.',
      'error_auth_generic': 'Nabigo ang pag-authenticate. Pakisubukan ulit.',
      'connection_lumad': 'Ano ang koneksyon mo sa mga wikang Lumad?',
      'heritage_learner': 'Natututo ako bilang heritage learner (wika ito ng aking pamilya)',
      'l2_learner': 'L2 learner ako (natututuhan ko ito bilang pangalawang wika)',
      'researcher_educator': 'Ako ay researcher o educator',
      'curious_culture': 'Nais ko lang malaman ang tungkol sa kultura',
      'exposure_question': 'Gaano ka kadalas makarinig o magsalita ng iyong katutubong wika?',
      'daily': 'Araw-araw',
      'occasionally': 'Paminsan-minsan',
      'rarely': 'Bihira',
      'never': 'Kailanman',
      'goal_question': 'Ano ang pangunahing layunin mo sa paggamit ng app na ito?',
      'fluent_goal': 'Upang maging bihasa sa wika',
      'elders_goal': 'Upang mas maunawaan ang aking mga nakatatanda',
      'preserve_goal': 'Upang mapanatili ang wika para sa susunod na henerasyon',
      'assessment_goal': 'Upang makapasa sa assessment',
      'learning_goal': 'Layunin sa Pagkatuto',
      'culture': 'Kultura',
      'travel': 'Paglalakbay',
      'ancestry': 'Ninuno',
      'community': 'Komunidad',
      'research': 'Pananaliksik',
      'agree_to': 'Sumasang-ayon ako sa',
      'terms': 'Mga Tuntunin',
      'and': 'at',
      'privacy_policy': 'Patakaran sa Privacy',
      'terms_conditions': 'Mga Tuntunin at Kondisyon',
      'close': 'ISARA',
      'legal_mansaka': 'Sa paggamit ng Lumad Lingua, sumasang-ayon kang igalang ang pamanang pangkultura ng mga Mansaka at iba pang tribong Lumad. Ipinagbabawal sa mga user ang maling paggamit, maling paglalarawan, o pagkomersyalisa ng tradisyonal na kaalaman nang walang wastong pahintulot mula sa tribo.',
      'legal_privacy': 'Mahalaga sa amin ang iyong privacy. Ang iyong data (pangalan, email, at lokasyon) ay gagamitin lamang upang mapabuti ang iyong karanasan sa pagkatuto at masubaybayan ang iyong progreso. Hindi namin ibebenta ang iyong personal na impormasyon sa mga third party.',

      // 2. User Profiles
      'tribe_member': 'Miyembro ng Tribo',
      'tribe_member_caps': 'MIYEMBRO NG TRIBO',
      'system_overseer': 'TAGAPANGASIWA NG SYSTEM',
      'researcher_staff': 'RESEARCHER STAFF',
      'wisdom_guide': 'GABAY SA KARUNUNGAN',
      'elder_pathfinder': 'GABAY NG MGA NAKATATANDA',
      'philippines': 'PILIPINAS',
      'unknown': 'Hindi Kilala',
      'total_xp': 'KABUUANG XP',
      'day_streak': 'SUNOD-SUNOD NA ARAW',
      'words': 'MGA SALITA',
      'vitality': 'LAKAS',
      'monitor': 'MONITOR',
      'students': 'MGA MAG-AARAL',
      'accuracy': 'KAWASTUHAN',
      'rating': 'RATING',
      'rank': 'RANGGO',
      'novice': 'BAGUHAN',
      'guardian': 'TAGAPAGBANTAY',
      'elder': 'NAKATATANDA',
      'elite': 'ELITE',
      'na': 'WALA',
      'journey_management': 'Pamamahala ng Paglalakbay',
      'edit_profile': 'I-edit ang Profile',
      'update_location_bio': 'I-update ang iyong lokasyon at bio',
      'wisdom_progression': 'Pag-unlad sa Karunungan',
      'wisdom_requirements': 'Tingnan ang requirements para sa susunod mong ranggo at titulo',
      'notification_sanctuary': 'Notification Center',
      'notification_desc': 'Pamahalaan ang alerts para sa daily goals at community messages',
      'data_privacy': 'Data at Privacy',
      'data_privacy_desc': 'I-export ang iyong contributions o pamahalaan ang seguridad ng account',
      'offline_wisdom': 'Offline Lessons',
      'offline_wisdom_desc': 'Pamahalaan ang naka-cache na lessons at audio files para magamit offline',
      'light_sanctuary': 'Light Theme',
      'dark_forest': 'Dark Theme',
      'switch_themes': 'Lumipat sa light at dark theme',
      'join_village': 'Sumali sa Village',
      'join_village_desc': 'Maglagay ng code para kumonekta sa iyong local educator',
      'welcome_village': 'Maligayang pagdating sa village! 🌿',
      'send_feedback': 'Magpadala ng Feedback',
      'feedback_desc': 'Mag-message sa iyong educators tungkol sa iyong learning journey',
      'simulation_mode': 'Simulation Mode',
      'exit_simulation': 'Lumabas sa Simulation',
      'admin_overview': 'Bumalik sa Admin Overview',
      'test_content_desc': 'Lumipat sa Learner view para subukan ang content',
      'log_out': 'MAG-LOG OUT',
      'choose_totem': 'Pumili ng Ancestral Totem',
      'upload_picture': 'Mag-upload ng Bagong Larawan',
      'remove_picture': 'Alisin ang Larawan',
      'pic_removed': 'Naalis na ang profile picture.',
      'uploading_totem': 'Ina-upload ang ancestral totem...',
      'pic_updated': 'Na-update na ang profile picture!',
      'upload_failed': 'Hindi nagtagumpay ang upload:',
      'choose_your_totem': 'Piliin ang Iyong Ancestral Totem',
      'failed_update': 'Hindi na-update:',
      'join_comm_village': 'Sumali sa isang community village',
      'village_code_entry': 'Ilagay ang 6-character code na ibinigay ng iyong educator para makasali sa kanilang community.',
      'code': 'CODE',
      'join': 'SUMALI',
      'village_code_label': 'VILLAGE CODE:',
      'activate_village': 'I-ACTIVATE ANG VILLAGE CODE',
      'village_activated': 'Na-activate na ang village! Maaari nang sumali ang mga estudyante sa iyong tribe. 🌿',
      'activation_failed': 'Hindi na-activate:',
      'edit_sacred_profile': 'I-edit ang Profile',
      'tribe_name': 'Pangalan ng Tribo',
      'location': 'Lokasyon',
      'location_locked': 'Naka-lock ang lokasyon',
      'bio': 'Pahayag/Bio',
      'bio_hint': 'Teaching philosophy o mga layunin para sa cultural heritage...',
      'save': 'I-SAVE',
      'feedback_prompt': 'May tanong o mungkahi? Direktang i-message ang iyong educators.',
      'type_message': 'I-type ang iyong mensahe...',
      'feedback_sent': 'Naipadala na ang feedback sa educators!',
      'send': 'IPADALA',
      'earned_artifacts': 'Mga Nakuhang Artifact',
      'no_treasures': 'Walang Nakuha',
      'no_artifacts_desc': 'Wala pang nadidiskubreng artifact ang miyembrong ito.',
      'error_artifacts': 'Error sa pag-load ng artifacts',

      // 3. Gamified Sessions
      'top_3': 'NASA TOP 3 KA! 🔥',
      'elders_wisdom': 'KARUNUNGAN NG MGA NAKATATANDA',
      'correct': 'Tama!',
      'slipped': 'Nadulas!',
      'sudden_death_survived': 'NALAMPASAN ANG SUDDEN DEATH! +1 Heart',
      'spirit_exhausted': 'UBOS NA ANG LAKAS',
      'strength_faded': 'Naubos ang iyong lakas bago matapos ang ritwal. Pero tandaan ang sinasabi ng mga nakatatanda:',
      'sacred_revival': 'PAGBABALIK NG LAKAS (50 ✨)',
      'review_slipped': 'BALIKAN ANG MGA NASIPYAT NA SALITA',
      'return_village': 'BUMALIK SA VILLAGE',
      'slipped_terms': 'MGA NASIPYAT NA SALITA',
      'reflect_before_return': 'Pag-isipan muna ang mga ito bago bumalik.',
      'got_it': 'NAINTINDIHAN KO',
      'badge_unlocked': 'Na-unlock ang Badge!',
      'perfect_scholar_desc': 'Nakuha mo ang Perfect Scholar badge dahil sa mahusay mong performance!',
      'awesome': 'Astig!',
      'loot_drop': 'May Nakuha Ka!',
      'add_vault': 'Idagdag sa Vault',
      'quote_1': 'Kahit matibay na puno ay yumuyuko sa bagyo para muling tumatag.',
      'quote_2': 'Mahabang paglalakbay ay may mga pahingahan.',
      'quote_3': 'Hindi nabubuo sa isang araw ang karunungan. Nabubuo ito sa mga aral ng bawat pagkakamali.',
      'quote_4': 'Matatag ang loob, tulad ng kawayan na muling tumayo matapos ang hangin.',
      'quote_5': 'Ang pagkatuto ay pagkadapa at muling pagbangon.',
      'leave_session': 'Umalis sa Session?',
      'leave_session_desc': 'Mawawala ang progress mo sa session na ito. Sigurado ka bang gusto mong umalis?',
      'keep_going': 'Magpatuloy',
      'quit': 'Umalis',
      'out_of_hearts': 'Wala nang Hearts! 💔',
      'restore_strength': 'Naging mahirap ang iyong journey. Gusto mo bang ibalik ang iyong lakas?',
      'cost': 'Halaga:',
      'not_enough_crystals': 'Kulang ang crystals!',
      'end_session': 'Tapusin ang Session',
      'restore_hearts': 'Ibalik ang Hearts',
      'confidence_question': 'Gaano ka kumpiyansa sa mga salitang kakatuon mo lang?',
      'very_confident': 'Lubos na kumpiyansa',
      'somewhat_confident': 'Medyo kumpiyansa',
      'bit_confused': 'Medyo nalilito',
      'need_practice': 'Kailangan ko pa ng pagsasanay',
      'difficulty_question': 'Angkop ba ang hirap ng lesson na ito?',
      'too_easy': 'Masyadong madali',
      'just_right': 'Sakto lang',
      'too_hard': 'Masyadong mahirap',
      'very_challenging': 'Napakahirap',
      'utility_question': 'Gaano kalamang na gagamitin mo ang mga salitang ito sa isang usapan?',
      'very_likely': 'Malamang na malamang',
      'possibly': 'Posible',
      'not_sure': 'Hindi sigurado',
      'unlikely': 'Malabo',

      // 4. Security
      'account_security': 'SEGURIDAD NG ACCOUNT',
      'account_protected': 'Protektado ang Account',
      'data_encryption_desc': 'Naka-encrypt ang iyong data gamit ang mga security protocol ng system.',
      'update_password': 'I-UPDATE ANG PASSWORD',
      'data_management': 'PAMAMAHALA NG DATA',
      'export_data': 'I-export ang Aking Data',
      'export_data_desc': 'Kopyahin ang JSON version ng iyong contributions at activity',
      'data_exported': 'Na-export at nakopya na ang data sa clipboard!',
      'export_failed': 'Hindi nagtagumpay ang export:',
      'activity_logs': 'Mga Activity Log',
      'review_security': 'Suriin ang iyong mga recent sign-in at security activity',
      'prepared_by_elders': 'ay inihahanda ng mga village elders.',
      'privacy_controls': 'MGA KONTROL SA PRIVACY',
      'public_profile': 'Pampublikong Profile',
      'public_profile_desc': 'Payagan ang ibang miyembro ng tribe na makita ang iyong achievements at rank',
      'usage_analytics': 'Usage Analytics',
      'share_anonymous_desc': 'Magbahagi ng anonymous data upang makatulong sa pagpapabuti ng platform',
      'current_password': 'Kasalukuyang Password',
      'new_password': 'Bagong Password',
      'incorrect_current_pass': 'Mali ang kasalukuyang password.',
      'password_updated': 'Matagumpay na na-update ang password!',
      'danger_zone': 'DANGER ZONE',
      'delete_account_desc': 'Permanenteng burahin ang iyong account at lahat ng kaugnay na contributions.',
      'delete_account_btn': 'I-DELETE ANG ACCOUNT',
      'sacrifice_account': 'I-delete ang Account?',
      'irreversible_desc': 'Hindi na mababawi ang action na ito. Mawawala ang lahat ng iyong progress, XP, at contributions. Ilagay ang iyong password upang kumpirmahin.',
      'incorrect_pass': 'Mali ang password.',
      'deletion_failed': 'Hindi nagtagumpay ang deletion:',
      'delete': 'I-DELETE',

      // 5. Multi-Player
      'ancestral_guardian': 'Tagapangalaga ng Ninuno',
      'lingua_duel': 'LINGUA DUEL',
      'duel_desc': 'Hamunin ang mga ancestral guardian o live learners sa ritwal na combat. Sumagot agad para depensahan ang iyong lakas at makakuha ng sinaunang crystal rewards.',
      'enter_arena': 'PASUKIN ANG ARENA',
      'retreat': 'BUMALIK',
      'seeking_opponent': 'NAGHAHANAP NG KALABAN...',
      'stirring_spirits': 'Pinupukaw ang mga espiritu ng arena...',
      'match_found': 'MAY KALABAN NA!',
      'prepare_combat': 'Ihanda ang isip para sa ritwal na combat.',
      'you_label': 'IKAW',
      'victory': 'TAGUMPAY!',
      'defeat': 'TALO',
      'victory_reward': '+150 XP  \u2022  +25 Mist Crystals',
      'defeat_desc': 'Subukan muli para ayusin ang iyong kaalaman.',
      'leave_arena': 'LUMABAS SA ARENA',
      'duel_question_prefix': 'Ano ang ibig sabihin ng "{word}"?',
      'duel_question_gm': 'Paano sabihin ang "Magandang Umaga" sa Mansaka?',
      'duel_question_land': 'Ano ang salitang Mansaka para sa "Lupa"?',

      // 6. Scenario Hub & Stories
      'scenario_stories': 'Mga Kuwento ng Scenario',
      'mastered': 'KABISADO NA',
      'choose_path_desc': 'Piliin ang iyong landas. Mahalaga ang bawat salita.',
      'search_stories': 'Maghanap ng mga kuwento...',
      'replay_story': 'ULITIN ANG KUWENTO',
      'start_scenario': 'SIMULAN ANG SCENARIO',

      // 7. Wisdom Sanctuary / Dictionary
      'definition': 'KAHULUGAN',
      'usage_example': 'HALIMBAWA NG PAGGAMIT',
      'example_usage': 'HALIMBAWA NG PAGGAMIT',
      'translation': 'SALIN',
      'daily_review': 'ARAW-ARAW NA REVIEW',
      'mastery_level_up': 'Tumaas ang Mastery Level!',
      'session_complete_msg': 'Tapos na ang Session!',
      'studied_all_cards': 'Napag-aralan mo na ang lahat ng cards.',
      'search_dictionary': 'Maghanap sa dictionary...',
      'search_cards': 'Maghanap ng cards...',
      'saved_label': 'NA-SAVE',
      'all_label': 'LAHAT',
      'no_saved_words': 'Wala ka pang nase-save na salita.',
      'no_search_results': 'Walang salitang tumutugma sa iyong paghahanap.',
      'sort_az': 'A - Z',
      'sort_za': 'Z - A',
      'sort_newest': 'Pinakabago Una',
      'sort_oldest': 'Pinakaluma Una',
      'share_label': 'IBAHAGI',
      'save_label': 'I-SAVE',
      'saved_caps': 'NA-SAVE NA',

      // 8. Leaderboard & Social
      'top_learners': 'MGA NANGUNGUNANG LEARNER',
      'weekly_fame': 'WEEKLY HALL OF FAME',
      'global_spirits': 'GLOBAL SPIRITS',
      'salute_sent': 'Naipadala na ang salute kay {name}!',
      'salute_failed': 'Hindi naipadala ang salute.',
      'incoming_kin_requests': 'MGA DUMATANG NA HILING SA KAMAG-ANAK',
      'accept': 'Tanggapin',
      'decline': 'Tanggihan',
      'add_kin': 'Ipadala ang Hiling',
      'already_kin': 'Kamag-anak Na',
      'kin_request_sent': 'Naipadala Na',
      'no_kin_yet': 'Wala pang kamag-anak. I-tap ang Imbitahan ang Kamag-anak upang maghanap at kumonekta!',
      'no_members_found': 'Walang nahanap na miyembro.',
      'salute_button': 'Magbigay-galang',
      'remove_kin': 'Alisin sa Kamag-anak',
      'rank_label': 'Ranggo',
      'spirit_score': 'Spirit Score',
      'village_label': 'Village',

      // 9. Dashboards & Rituals
      'good_morning': 'Magandang Umaga',
      'welcome_back': 'Maligayang Pagbabalik',
      'daily_rituals': 'MGA ARAW-ARAW NA RITWAL',
      'attention_needed': 'Kailangan ng Atensyon',
      'village_challenge': 'HAMON NG VILLAGE',
      'challenge_completed': 'Nakumpleto mo na ang challenge ngayong araw!',
      'home': 'HOME',
      'you': 'IKAW',
      'learn': 'MATUTO',
      'dashboard': 'DASHBOARD',
      'users': 'MGA USER',

      // 10. Admin & Educator Tools
      'stats_refreshed': 'Na-refresh na ang platform stats',
      'wotd_rotated': 'Na-update na ang Word of the Day',
      'confirm_wotd': 'KUMPIRMAHIN ANG WOTD',
      'approve_all': 'APRUBAHAN LAHAT',
      'analytics_report': 'Analytics Report ng Educator',
      'system_overview': 'Pangkalahatang-ideya ng System',
      'dialect_dist': 'Distribusyon ng mga Diyalekto',
      'add_word': 'Magdagdag ng Salita',
      'add_blank': 'Magdagdag ng Blankong Sagot',
      'true_label': 'TAMA',
      'false_label': 'MALI',
      'pedagogical_analytics': 'PEDAGOGICAL ANALYTICS',
      'learning_eco_health': 'KALUSUGAN NG LEARNING ECOSYSTEM',
      'retention_rate': 'Retention Rate',
      'active_terms': 'Mga Aktibong Salita',
      'lesson_heatmaps': 'LESSON HEATMAPS (MGA PUNTONG NAHIHIRAPAN)',
      'student_stumbles_empty': 'Sariwa pa ang landas. Wala pang naitalang hirap ang mga estudyante.',
      'srs_mastery_title': 'SPACED REPETITION (SRS) MASTERY',
      'mastery_box_dist': 'Distribusyon ng Mastery Box',
      'failed_sync_wisdom': 'Hindi na-sync ang karunungan: {error}',
      'retry_sync': 'SUBUKAN MULI ANG SYNC',
      'ancestral_lesson_default': 'Sinaunang Lesson',
      'box_label': 'BOX',
      'xp_growth_trends': 'PAGLAKI NG XP NG MGA USER (7 ARAW)',
      'pronunciation_by_dialect': 'KAWASTUHAN NG PAGBIGKAS AYON SA DIYALEKTO',
      'pronunciation_by_location': 'KAWASTUHAN NG PAGBIGKAS AYON SA LOKASYON',
      'aggregate_xp_growth': 'KABUUANG PAGLAKI NG XP',
      'insufficient_voice_data': 'Kulang ang data ng boses.',
      'no_xp_activity': 'Walang naitalang aktibidad ng XP.',

      // 11. Miscellaneous
      'no_audio': 'Walang available na audio',
      'no_translation': 'Walang nahanap na salin.',
      'ancestral_gallery': 'Gallery ng mga Ninuno',
      'view_sacred_artifacts': 'Tingnan ang mga Sagradong Artifact',
      'saved_locally_sync': 'Na-save nang lokal. Mag-sync kapag online na.',
      'offline_synced': 'Matagumpay na na-sync ang mga offline draft!',

      // 12. Achievements
      'ancestral_honors': 'Mga Karangalan ng Ninuno',
      'your_legacy': 'Iyong Pamana',
      'legacy_desc': 'Pagsubaybay sa iyong paglalakbay sa pamamagitan ng sinaunang karunungan.',
      'collected': 'Nakuha',
      'total_label': 'Kabuuan',
      'vault_locked': 'Nakandado ang Vault',
      'unlock_treasures': 'Kumpletuhin ang mga lesson para ma-unlock ang mga yaman ng kultura.',

      // 13. Warriors Circle
      'warriors_circle': 'KORONG NG MGA MANDIRIGMA',
      'search_members': 'Maghanap ng mga miyembro...',
      'invite_kin': 'IMBITAHAN ANG KAMAG-ANAK',
      'warrior_label': 'MANDIRIGMA',
      'duel_btn': 'DUEL',

      // 14. Community Feed
      'living_feed': 'BUHAY NA FEED',
      'community_quiet': 'Tahimik ang komunidad... sa ngayon. 🌿',
      'comments_label': 'Mga Komento',
      'conversation_soon': 'Magsisimula na ang usapan soon... 🌿',
      'add_comment_hint': 'Magdagdag ng komento...',
      'sharing_update': 'Ibinabahagi ang update ni {name}...',

      // 15. Ancestral Vault Shop
      'ancestral_vault_caps': 'VAULT NG MGA NINUNO',
      'vault_sealed': 'Kasalukuyang nakasara ang vault.\nMagbalik pagkatapos ng iyong susunod na ritwal.',
      'ancestral_blessing': 'Biyaya ng mga ninuno',
      'unlock_caps': 'I-UNLOCK',
      'not_enough_crystals_exchange': 'Kailangan mo ng mas maraming Mist Crystals para sa exchange na ito.',
      'sacred_exchange': 'Sagradong Exchange',
      'owned_caps': 'NAKUHA NA',
      'exchange_confirm': 'Nais mo bang gumastos ng {cost} Mist Crystals para ma-unlock ang {item}?',
      'processing': 'Pinoproseso...',
      'legacy_unlocked': 'NA-UNLOCK NA ANG PAMANA',
      'tap_return_vault': 'Pindutin para bumalik sa vault',



      // 17. Streak History
      'streak_journey': 'PAGLALAKBAY NG STREAK',
      'on_fire': 'Nag-aapoy ka!',
      'start_journey_today': 'Simulan ang iyong paglalakbay ngayon!',
      'streak_desc': 'Patuloy na matuto araw-araw para lumaki ang iyong streak.',
      'streak_shields': 'MGA SHIELD NG STREAK',
      'available': 'Available',
      'get_more': 'KUMUHA PA',
      'activity_map': 'MAPA NG AKTIBIDAD',
      'milestones_caps': 'MGA MILESTONE',
      'one_week': 'Isang Linggo',
      'month_wisdom': 'Buwan ng Karunungan',
      'tribe_guardian_milestone': 'Tagapangalaga ng Tribo',
      'claim_caps': 'KUNIN',
      'claimed_msg': 'Nakuha na ang {reward}! 🎉',
      'crystals_reward': '{count} na Crystals',

      // 18. Artifact Detail
      'lore_legend': 'Karunungan at Alamat',
      'origin_craft': 'Pinagmulan at Likha',
      'share_heritage': 'IBAHAGI ANG PAMANA',
      'sharing_lineage': 'Ibinabahagi ang kwento ng lahi...',
      'no_legend_yet': 'Wala pang alamat. Tumuklas ng higit pang mga ritwal upang ipakita ang buong kwento ng sagradong bagay na ito.',

      // 19. Admin Overview
      'village_pulse': 'PULSO NG VILLAGE',
      'platform_stats': 'STATS NG PLATAPORMA',
      'total_users': 'Kabuuang Users',
      'words_added': 'Mga Salitang Idinagdag',
      'audio_clips': 'Mga Audio Clip',
      'manage_label': 'PAMAHALAAN',
      'dictionary_label': 'Dictionary',
      'lessons_label': 'Mga Lesson',
      'advanced_analytics': 'ADVANCED PEDAGOGICAL ANALYTICS',
      'system_health_label': 'KALUSUGAN NG SYSTEM',
      'user_growth_label': 'PAGLAKI NG USERS (huling 7 araw)',
      'gamification_economics': 'GAMIFICATION at EKONOMIYA',
      'warrior_circle_ops': 'OPS NG WARRIOR CIRCLE',
      'manage_seasons_desc': 'Pamahalaan ang mga season, presyo sa shop, at duel moderation.',
      'go_economics_hub': 'PUMUNTA SA ECONOMICS HUB',

      'force_rotation': 'PWERSAHING PALITAN',
      'resume_auto': 'IBALIK SA AUTO',
      'pick_manually': 'PUMILI NANG MANWAL',
      'good_morning_name': 'Magandang\nUmaga,\n{name}!',
      'select_language': 'Pumili ng Wika',
      'english': 'English',
      'filipino': 'Filipino',
      'bisaya': 'Bisaya',

      // 20. System Guide
      'system_nav_guide': 'GABAY SA PAG-NAVIGATE NG SYSTEM',
      'welcome_lumad_lingua': 'Maligayang Pagdating sa Lumad Lingua',
      'guide_title_1': '1. Oryentasyon sa Kultural na Pamana',
      'guide_desc_1': 'Isang pangkalahatang-ideya ng ating katutubong komunidad, na nagpapaliwanag sa kahalagahan ng pagpapanatili ng ating mga sagradong wika at tradisyon.',
      'guide_title_2': '2. Roadmap ng Pagkatuto',
      'guide_desc_2': 'Gabay sa interactive na proseso ng pag-unlad. Umabante sa pamamagitan ng mga tribal units at scenario hubs.',
      'guide_title_3': '3. Mga Alituntunin sa Pagbigkas',
      'guide_desc_3': 'Alamin kung paano gamitin ang mikropono para sa pagsusuri ng pagbigkas. Makinig sa mga nakatatanda para makuha ang tamang tono.',
      'guide_title_4': '4. Paggamit ng Dictionary',
      'guide_desc_4': 'Maghanap sa ating malawak na imbakan ng mga salita. Galugarin ang mga halimbawa at salin sa Ingles o Filipino.',
      'guide_title_5': '5. Pakikilahok sa Komunidad',
      'guide_desc_5': 'Unawain ang XP reward cycle, mga ranggo, at badges. Hamunin ang iba sa mga duel at magpadala ng Tribal Salute.',
      'guide_title_6': '6. Privacy at Pagpapatunay',
      'guide_desc_6': 'Linaw sa pamamahala ng komunidad. Alamin kung paano pinoprotektahan at pinapatunayan ng mga elders ang mga naitalang data.',

      // 21. Onboarding Narrative
      'onboarding_title_1': 'Ang mga Alingawngaw ay Naglalaho',
      'onboarding_sub_1': 'ANG ATING MGA SINAUNANG TINIG',
      'onboarding_desc_1': 'Ang mga sagradong wika ng ating mga tribo ay naglalaho na parang hamog sa bukang-liwayway. Pinili ka upang tipunin ang mga natitirang alingawngaw.',
      'onboarding_title_2': 'Ang Ancestral Vault',
      'onboarding_sub_2': 'SAGRADONG KARUNUNGAN',
      'onboarding_desc_2': 'Bawat salitang natututuhan mo ay nagbabalik ng bahagi ng ating kasaysayan. I-unlock ang mga sinaunang artifact at muling buuin ang pamana.',
      'onboarding_title_3': 'Iyong Paglalakbay sa Tribo',
      'onboarding_sub_3': 'NAGHIHINTAY ANG KARUNUNGAN',
      'onboarding_desc_3': 'Sumali sa Warriors\' Circle at makipagkumpetensya sa mga duel. Mahaba ang landas sa pagiging bihasa, ngunit ang mga nakatatanda ay kasama mo.',
      'begin_ritual': 'SIMULAN ANG RITWAL',
      'reset_in': 'MAG-RE-RESET SA LOOB NG {time}',
      'challenge_hub': 'SENTRO NG MGA HAMON',
      'current_lesson': 'KASALUKUYANG LESSON',
      'lesson_progress': 'Progreso ng Lesson',
      'review_ascent': 'BALIKAN ANG PAG-AKYAT',
      'continue_ascent': 'IPAGPATULOY ANG PAG-AKYAT',
      'start_your_journey': 'Simulan ang Iyong Paglalakbay',
      'begin_ascent_desc': 'Simulan ang iyong pag-akyat sa kabundukan at tuklasin ang pamanang Lumad.',
      'start_unit_1': 'SIMULAN ANG UNIT 1',
      'botanical_archivists': 'Ang pinaka-aktibong botanical archivists ng season.',
      'view_all': 'TINGNAN LAHAT',
      'quiet_mountains': 'Tahimik na Kabundukan',
      'no_climbers': 'Wala pang umaakyat! Maging una sa pagsisimula ng pag-akyat.',
      'archive_xp': 'ARCHIVE XP',
      'keep_flame_alive': 'Panatilihing buhay ang apoy!',
      'ritual_empty_desc': 'Walang ritwal ngayon. Magbalik muli para sa mas maraming hamon!',
    },
    'bis': {
      // 1. Onboarding & Auth
      'app_name': 'Lumad Lingua',
      'step': 'Lakang',
      'identity': 'Pagkaila',
      'roots': 'Mga Gamut',
      'path': 'Dalan',
      'ritual': 'Ritwal',
      'welcome_guest': 'Maayong pag-abot, Halangdong Bisita!',
      'invited_as': 'Giimbitar ka isip',
      'for': 'para sa',
      'already_have_account': 'Naa na kay account?',
      'dont_have_account': 'Wala pa kay account?',
      'sign_in': 'Mag-sign In',
      'sign_up': 'Mag-sign Up',
      'signing_in': 'Nag-sign in...',
      'waiting': 'Naghulat...',
      'continue': 'Padayon',
      'next_ritual': 'Sunod: Ritwal',
      'back': 'Balik',
      'or': 'O',
      'sign_in_google': 'Mag-sign in gamit ang Google',
      'quick_join_google': 'Dali nga Pagsali gamit ang Google',
      'email_address': 'Email Address',
      'password': 'Password',
      'confirm_password': 'Kumpirmaha ang Password',
      'display_name': 'Pangalan nga Ipakita',
      'province': 'Probinsya',
      'municipality': 'Munisipyo',
      'select_province': 'Pilia ang Probinsya',
      'select_municipality': 'Pilia ang Munisipyo',
      'village_code_optional': 'Village Code (Opsyonal)',
      'village_code_hint': 'Ibutang ang code nga gihatag sa imong educator aron makaapil sa ilang community village.',
      'fill_all_fields': 'Palihog sulati og sakto ang tanang field',
      'complete_fields_terms': 'Palihog kompletoha ang tanang field ug dawata ang Terms',
      'native_language': 'Katutubong Pinulongan',
      'select_native_language': 'Pilia ang Katutubong Pinulongan',
      'valid_email': 'Kinahanglan valid ang email',
      'password_length': 'Kinahanglan labing menos 6 ka character ang password',
      'passwords_dont_match': 'Dili parehas ang mga password',
      'tribe_name_length': 'Kinahanglan labing menos 3 ka character ang ngalan sa tribe',
      'invalid_email_format': 'Dili valid ang format sa email',
      'password_too_short': 'Mubo ra kaayo ang password',
      'forgot_password': 'Nakalimot sa Password?',
      'reset_password_title': 'I-reset ang Password',
      'reset_password_desc': 'Ibutang ang imong nakarehistro nga email ug ipadala namo ang link aron ma-reset ang imong password.',
      'send_reset_link': 'Ipadala ang Link',
      'cancel': 'Kanselahon',
      'reset_email_sent': 'Naipadala na sa imong email ang link sa pag-reset sa password.',
      'error_user_not_found': 'Walay nakit-an nga account gamit kini nga email.',
      'error_wrong_password': 'Sayop nga password. Palihug sulayi pag-usab.',
      'error_invalid_credential': 'Dili balido nga email o password. Palihug tan-awa ang imong impormasyon.',
      'error_email_already_in_use': 'Naa nay nag-gamit sa kini nga email address.',
      'error_invalid_email': 'Palihug pagbutang og balido nga email address.',
      'error_user_disabled': 'Gi-disable kini nga account. Palihug pakigsulti sa suporta.',
      'error_too_many_requests': 'Daghan ra kaayong nasayop nga sulay. Palihug sulayi pag-usab unya.',
      'error_network_failed': 'Nawala ang koneksyon sa internet. Palihug tan-awa ang imong internet.',
      'error_weak_password': 'Mabuak ra o huyang ra kaayo ang password. Pagpili og mas kusog nga password.',
      'error_operation_not_allowed': 'Gidili o naka-disable kini nga pamaagi sa pag-sign in.',
      'error_auth_generic': 'Napasagdan o napakyas ang pag-authenticate. Palihug sulayi pag-usab.',
      'connection_lumad': 'Unsa ang imong koneksyon sa mga pinulongang Lumad?',
      'heritage_learner': 'Heritage learner ko (pinulongan kini sa akong pamilya)',
      'l2_learner': 'L2 learner ko (ikaduhang pinulongan nako kini nga makat-onan)',
      'researcher_educator': 'Researcher o educator ko',
      'curious_culture': 'Nainteres lang ko nga makaila pa sa kultura',
      'exposure_question': 'Unsa ka kanunay makadungog o makasulti sa imong katutubong pinulongan?',
      'daily': 'Adlaw-adlaw',
      'occasionally': 'Usahay',
      'rarely': 'Panagsa ra',
      'never': 'Wala gayud',
      'goal_question': 'Unsa ang imong pangunang tumong sa paggamit niini nga app?',
      'fluent_goal': 'Aron mahimong hanas sa pinulongan',
      'elders_goal': 'Aron mas masabtan nako ang akong mga katigulangan',
      'preserve_goal': 'Aron mapreserba ang pinulongan para sa sunod nga henerasyon',
      'assessment_goal': 'Aron makapasar sa assessment',
      'learning_goal': 'Tumong sa Pagkat-on',
      'culture': 'Kultura',
      'travel': 'Pagbiyahe',
      'ancestry': 'Kagikanan',
      'community': 'Komunidad',
      'research': 'Panukiduki',
      'agree_to': 'N mouyon ko sa',
      'terms': 'Mga Kondisyon',
      'and': 'ug',
      'privacy_policy': 'Patakaran sa Privacy',
      'terms_conditions': 'Mga Tuntunin ug Kondisyon',
      'close': 'ISIRA',
      'legal_mansaka': 'Sa paggamit sa Lumad Lingua, mouyon ka nga respetuhon ang kultural nga panulondon sa mga Mansaka ug uban pang tribong Lumad. Gidili sa mga user ang sayop nga paggamit, pagpasabot, o pagkomersyalisa sa tradisyonal nga kahibalo nga walay hustong pagtugot gikan sa tribo.',
      'legal_privacy': 'Importante para kanamo ang imong privacy. Ang imong data (ngalan, email, ug lokasyon) gamiton lamang aron mapaayo ang imong kasinatian sa pagkat-on ug masubay ang imong progreso. Dili namo ibaligya ang imong personal na impormasyon ngadto sa mga third party.',

      // 2. User Profiles
      'tribe_member': 'Miyembro sa Tribo',
      'tribe_member_caps': 'MIYEMBRO SA TRIBO',
      'system_overseer': 'TAGAPANGASIWA SA SYSTEM',
      'researcher_staff': 'RESEARCHER STAFF',
      'wisdom_guide': 'GIYA SA KAALAM',
      'elder_pathfinder': 'GIYA SA MGA KATIGULANGAN',
      'philippines': 'PILIPINAS',
      'unknown': 'Wala Nailhi',
      'total_xp': 'KINATIBUK-ANG XP',
      'day_streak': 'SUNOD-SUNOD NGA ADLAW',
      'words': 'MGA PULONG',
      'vitality': 'KUSOG',
      'monitor': 'MONITOR',
      'students': 'MGA ESTUDYANTE',
      'accuracy': 'KASAKTO',
      'rating': 'RATING',
      'rank': 'RANGGO',
      'novice': 'BAG-ONG MAGTUTUN-AN',
      'guardian': 'TIGBANTAY',
      'elder': 'KATIGULANGAN',
      'elite': 'ELITE',
      'na': 'WALA',
      'journey_management': 'Pagdumala sa Panaw',
      'edit_profile': 'I-edit ang Profile',
      'update_location_bio': 'I-update ang imong lokasyon ug bio',
      'wisdom_progression': 'Pag-uswag sa Kaalam',
      'wisdom_requirements': 'Tan-awa ang requirements para sa sunod nimong ranggo ug titulo',
      'notification_sanctuary': 'Notification Center',
      'notification_desc': 'I-manage ang alerts para sa daily goals ug community messages',
      'data_privacy': 'Data ug Privacy',
      'data_privacy_desc': 'I-export ang imong contributions o i-manage ang security sa account',
      'offline_wisdom': 'Offline Lessons',
      'offline_wisdom_desc': 'I-manage ang cached lessons ug audio files para magamit offline',
      'light_sanctuary': 'Light Theme',
      'dark_forest': 'Dark Theme',
      'switch_themes': 'Pagbalhin tali sa light ug dark theme',
      'join_village': 'Apil sa Village',
      'join_village_desc': 'Ibutang ang code aron makakonekta sa imong local educator',
      'welcome_village': 'Maayong pag-abot sa village! 🌿',
      'send_feedback': 'Magpadala og Feedback',
      'feedback_desc': 'I-message ang imong educators bahin sa imong learning journey',
      'simulation_mode': 'Simulation Mode',
      'exit_simulation': 'Gawas sa Simulation',
      'admin_overview': 'Balik sa Admin Overview',
      'test_content_desc': 'Pagbalhin sa Learner view aron masulayan ang content',
      'log_out': 'MAG-LOG OUT',
      'choose_totem': 'Pilia ang Ancestral Totem',
      'upload_picture': 'Mag-upload og Bag-ong Litrato',
      'remove_picture': 'Kuhaa ang Litrato',
      'pic_removed': 'Natangtang na ang profile picture.',
      'uploading_totem': 'Gi-upload ang ancestral totem...',
      'pic_updated': 'Na-update na ang profile picture!',
      'upload_failed': 'Napakyas ang upload:',
      'choose_your_totem': 'Pilia ang Imong Ancestral Totem',
      'failed_update': 'Napakyas ang pag-update:',
      'join_comm_village': 'Apil sa usa ka community village',
      'village_code_entry': 'Ibutang ang 6-character code nga gihatag sa imong educator aron makaapil sa ilang community.',
      'code': 'CODE',
      'join': 'APIL',
      'village_code_label': 'VILLAGE CODE:',
      'activate_village': 'I-ACTIVATE ANG VILLAGE CODE',
      'village_activated': 'Na-activate na ang village! Makaapil na ang mga estudyante sa imong tribe. 🌿',
      'activation_failed': 'Napakyas ang activation:',
      'edit_sacred_profile': 'I-edit ang Profile',
      'tribe_name': 'Ngalan sa Tribo',
      'location': 'Lokasyon',
      'location_locked': 'Naka-lock ang lokasyon',
      'bio': 'Pahayag/Bio',
      'bio_hint': 'Teaching philosophy o mga tumong para sa cultural heritage...',
      'save': 'I-SAVE',
      'feedback_prompt': 'Naa kay pangutana o sugyot? Direktang i-message ang imong educators.',
      'type_message': 'I-type ang imong mensahe...',
      'feedback_sent': 'Na-send na ang feedback sa educators!',
      'send': 'I-SEND',
      'earned_artifacts': 'Mga Nakuhang Artifact',
      'no_treasures': 'Wala pay Nakuha',
      'no_artifacts_desc': 'Wala pa’y artifact nga nadiskobrehan niini nga miyembro.',
      'error_artifacts': 'Error sa pag-load sa artifacts',

      // 3. Gamified Sessions
      'top_3': 'NAA KA SA TOP 3! 🔥',
      'elders_wisdom': 'KAALAM SA MGA KATIGULANGAN',
      'correct': 'Sakto!',
      'slipped': 'Nasipyat!',
      'sudden_death_survived': 'NALAMPASAN ANG SUDDEN DEATH! +1 Heart',
      'spirit_exhausted': 'HUTDAN NA OG KUSOG',
      'strength_faded': 'Nahurot ang imong kusog sa wala pa matapos ang ritwal. Pero hinumdumi ang giingon sa mga katigulangan:',
      'sacred_revival': 'PAGBALIK SA KUSOG (50 ✨)',
      'review_slipped': 'BALIKA ANG MGA NASIPYAT NGA PULONG',
      'return_village': 'BALIK SA VILLAGE',
      'slipped_terms': 'MGA NASIPYAT NGA PULONG',
      'reflect_before_return': 'Pamalandungi kini una pa mubalik.',
      'got_it': 'NASABTAN KO',
      'badge_unlocked': 'Na-unlock ang Badge!',
      'perfect_scholar_desc': 'Nakuha nimo ang Perfect Scholar badge tungod sa maayo nimong performance!',
      'awesome': 'Maayo kaayo!',
      'loot_drop': 'Nakakuha Ka!',
      'add_vault': 'Idugang sa Vault',
      'quote_1': 'Bisan ang lig-on nga kahoy moliko sa bagyo aron mas molig-on pa.',
      'quote_2': 'Ang taas nga panaw adunay mga panahon sa pagpahulay.',
      'quote_3': 'Dili matukod sa usa ka adlaw ang kaalam. Nakat-onan kini sa matag sayop.',
      'quote_4': 'Lig-on ang espiritu, sama sa kawayan nga mobarog pag-usab human sa hangin.',
      'quote_5': 'Ang pagkat-on kay pagkapandol ug pagbangon pag-usab.',
      'leave_session': 'Mogawas sa Session?',
      'leave_session_desc': 'Mawala ang imong progress sa session. Sigurado ka nga mogawas ka?',
      'keep_going': 'Padayon',
      'quit': 'Gawas',
      'out_of_hearts': 'Nahurot na ang Hearts! 💔',
      'restore_strength': 'Nalisdan na ang imong journey. Gusto ba nimo ibalik ang imong kusog?',
      'cost': 'Gasto:',
      'not_enough_crystals': 'Kulang ang crystals!',
      'end_session': 'Tapuson ang Session',
      'restore_hearts': 'Ibalik ang Hearts',
      'confidence_question': 'Unsa ka kumpiyansa sa mga pulong nga bag-o nimong nakat-onan?',
      'very_confident': 'Kumpiyansa kaayo',
      'somewhat_confident': 'Medyo kumpiyansa',
      'bit_confused': 'Medyo nalibog',
      'need_practice': 'Kinahanglan pa nako og praktis',
      'difficulty_question': 'Sakto ba ang kalisod sa lesson?',
      'too_easy': 'Sayon ra kaayo',
      'just_right': 'Sakto ra',
      'too_hard': 'Lisod ra kaayo',
      'very_challenging': 'Lisod kaayo',
      'utility_question': 'Unsa ka dako ang posibilidad nga gamiton nimo kini nga mga pulong sa panag-istorya?',
      'very_likely': 'Dako kaayo og posibilidad',
      'possibly': 'Posible',
      'not_sure': 'Dili sigurado',
      'unlikely': 'Gamay ang posibilidad',

      // 4. Security
      'account_security': 'SEGURIDAD SA ACCOUNT',
      'account_protected': 'Protektado ang Account',
      'data_encryption_desc': 'Naka-encrypt ang imong data gamit ang security protocols sa system.',
      'update_password': 'I-UPDATE ANG PASSWORD',
      'data_management': 'PAGDUMALA SA DATA',
      'export_data': 'I-export ang Akong Data',
      'export_data_desc': 'Kopyaha ang JSON version sa imong contributions ug activity',
      'data_exported': 'Na-export ug nakopya na ang data sa clipboard!',
      'export_failed': 'Napakyas ang export:',
      'activity_logs': 'Mga Activity Log',
      'review_security': 'Susiha ang imong recent sign-in ug security activity',
      'prepared_by_elders': 'giandam sa mga village elders.',
      'privacy_controls': 'MGA KONTROL SA PRIVACY',
      'public_profile': 'Public Profile',
      'public_profile_desc': 'Tugoti ang ubang miyembro sa tribe nga makita ang imong achievements ug rank',
      'usage_analytics': 'Usage Analytics',
      'share_anonymous_desc': 'I-share ang anonymous data aron makatabang sa pagpaayo sa platform',
      'current_password': 'Kasamtangang Password',
      'new_password': 'Bag-ong Password',
      'incorrect_current_pass': 'Sayop ang kasamtangang password.',
      'password_updated': 'Malampusong na-update ang password!',
      'danger_zone': 'DANGER ZONE',
      'delete_account_desc': 'Permanenteng i-delete ang imong account ug tanang related contributions.',
      'delete_account_btn': 'I-DELETE ANG ACCOUNT',
      'sacrifice_account': 'I-delete ang Account?',
      'irreversible_desc': 'Dili na mabawi kini nga action. Mawala ang tanan nimong progress, XP, ug contributions. Ibutang ang imong password aron makumpirma.',
      'incorrect_pass': 'Sayop ang password.',
      'deletion_failed': 'Napakyas ang deletion:',
      'delete': 'I-DELETE',

      // 5. Multi-Player
      'ancestral_guardian': 'Tigbantay sa Kagikanan',
      'lingua_duel': 'LINGUA DUEL',
      'duel_desc': 'Hagita ang mga ancestral guardian o live learners sa ritwal nga combat. Tubag dayon para depensahan ang imong kusog ug makakuha og karaan nga crystal rewards.',
      'enter_arena': 'SULOD SA ARENA',
      'retreat': 'BALIK',
      'seeking_opponent': 'NANGITA OG KALABAN...',
      'stirring_spirits': 'Gipukaw ang mga espiritu sa arena...',
      'match_found': 'NAA NAY KALABAN!',
      'prepare_combat': 'Ihanda ang huna-huna para sa ritwal nga combat.',
      'you_label': 'IKAW',
      'victory': 'DAUG!',
      'defeat': 'PELDI',
      'victory_reward': '+150 XP  \u2022  +25 Mist Crystals',
      'defeat_desc': 'Sulayi pag-usab para mapaayo ang imong kaalam.',
      'leave_arena': 'GAWAS SA ARENA',
      'duel_question_prefix': 'Unsa ang pasabot sa "{word}"?',
      'duel_question_gm': 'Unsaon pag-ingon og "Maayong Buntag" sa Mansaka?',
      'duel_question_land': 'Unsa ang pulong nga Mansaka para sa "Yuta"?',

      // 6. Scenario Hub & Stories
      'scenario_stories': 'Mga Sugilanon sa Scenario',
      'mastered': 'KABALO NA',
      'choose_path_desc': 'Pilia ang imong dalan. Importante ang matag pulong.',
      'search_stories': 'Pangitaa ang mga sugilanon...',
      'replay_story': 'BALIK-BALIKA ANG SUGILANON',
      'start_scenario': 'SUGDAN ANG SCENARIO',

      // 7. Wisdom Sanctuary / Dictionary
      'definition': 'KAHULUGAN',
      'usage_example': 'PANANGLITAN SA PAGGAMIT',
      'example_usage': 'PANANGLITAN SA PAGGAMIT',
      'translation': 'HUBAD',
      'daily_review': 'ADLAW-ADLAW NGA REVIEW',
      'mastery_level_up': 'Misaka ang Mastery Level!',
      'session_complete_msg': 'Nahuman na ang Session!',
      'studied_all_cards': 'Nahibaw-an na nimo ang tanang cards.',
      'search_dictionary': 'Pangitaa sa dictionary...',
      'search_cards': 'Pangitaa ang cards...',
      'saved_label': 'NA-SAVE',
      'all_label': 'TANAN',
      'no_saved_words': 'Wala pa kay na-save nga mga pulong.',
      'no_search_results': 'Walay pulong nga nitugma sa imong gipangita.',
      'sort_az': 'A - Z',
      'sort_za': 'Z - A',
      'sort_newest': 'Pinakabago Una',
      'sort_oldest': 'Pinakaluma Una',
      'share_label': 'I-SHARE',
      'save_label': 'I-SAVE',
      'saved_caps': 'NA-SAVE NA',

      // 8. Leaderboard & Social
      'top_learners': 'MGA NANGUNA NGA LEARNER',
      'weekly_fame': 'WEEKLY HALL OF FAME',
      'global_spirits': 'GLOBAL SPIRITS',
      'salute_sent': 'Na-send na ang salute kang {name}!',
      'salute_failed': 'Napakyas sa pag-send sa salute.',
      'rank_label': 'Ranggo',
      'spirit_score': 'Spirit Score',
      'village_label': 'Village',

      // 9. Dashboards & Rituals
      'good_morning': 'Maayong Buntag',
      'welcome_back': 'Maayong Pagbalik',
      'daily_rituals': 'MGA ADLAW-ADLAW NGA RITWAL',
      'attention_needed': 'Kinahanglan og Atensyon',
      'village_challenge': 'HAGIT SA VILLAGE',
      'challenge_completed': 'Nahuman na nimo ang challenge karong adlawa!',
      'home': 'HOME',
      'you': 'IKAW',
      'learn': 'PAGKAT-ON',
      'dashboard': 'DASHBOARD',
      'users': 'MGA USER',

      // 10. Admin & Educator Tools
      'stats_refreshed': 'Na-refresh na ang platform stats',
      'wotd_rotated': 'Na-update na ang Word of the Day',
      'confirm_wotd': 'KUMPIRMAHA ANG WOTD',
      'approve_all': 'I-APPROVE ANG TANAN',
      'analytics_report': 'Analytics Report sa Educator',
      'system_overview': 'Kinatibuk-ang Overview sa System',
      'dialect_dist': 'Distribusyon sa mga Diyalekto',
      'add_word': 'Magdugang og Pulong',
      'add_blank': 'Magdugang og Blankong Tubag',
      'true_label': 'TINUOD',
      'false_label': 'SAYOP',
      'pedagogical_analytics': 'PEDAGOGICAL ANALYTICS',
      'learning_eco_health': 'KAHIMTANG SA LEARNING ECOSYSTEM',
      'retention_rate': 'Retention Rate',
      'active_terms': 'Mga Aktibong Pulong',
      'lesson_heatmaps': 'LESSON HEATMAPS (MGA PUNTO NGA NAGLISOD)',
      'student_stumbles_empty': 'Lab-as pa ang dalan. Wala pay natala nga kalisod ang mga estudyante.',
      'srs_mastery_title': 'SPACED REPETITION (SRS) MASTERY',
      'mastery_box_dist': 'Distribusyon sa Mastery Box',
      'failed_sync_wisdom': 'Napakyas sa pag-sync sa kaalam: {error}',
      'retry_sync': 'SULAYI PAG-USAB ANG SYNC',
      'ancestral_lesson_default': 'Karaan nga Lesson',
      'box_label': 'BOX',
      'xp_growth_trends': 'PAGDAGHAN SA XP SA MGA USER (7 KA ADLAW)',
      'pronunciation_by_dialect': 'KASAKTO SA PAGLITOK PINASIKAD SA DIYALEKTO',
      'pronunciation_by_location': 'KASAKTO SA PAGLITOK PINASIKAD SA LOKASYON',
      'aggregate_xp_growth': 'KINATIBUK-ANG PAGDAGHAN SA XP',
      'insufficient_voice_data': 'Dili sapat ang data sa tingog.',
      'no_xp_activity': 'Walay natala nga aktibidad sa XP.',

      // 11. Miscellaneous
      'no_audio': 'Walay available nga audio',
      'no_translation': 'Walay nakit-an nga hubad.',
      'ancestral_gallery': 'Gallery sa mga Kagikanan',
      'view_sacred_artifacts': 'Tan-awa ang mga Sagradong Artifact',
      'saved_locally_sync': 'Na-save locally. Mag-sync kung online na.',
      'offline_synced': 'Malampusong na-sync ang mga offline draft!',

      // 12. Achievements
      'ancestral_honors': 'Mga Dungog sa Kagikanan',
      'your_legacy': 'Imong Kabilin',
      'legacy_desc': 'Pagsunod sa imong panaw pinaagi sa kabilin sa kaalam.',
      'collected': 'Nakuha',
      'total_label': 'Tanan',
      'vault_locked': 'Naka-lock ang Vault',
      'unlock_treasures': 'Kompletoha ang mga lesson para ma-unlock ang mga bahandi sa kultura.',

      // 13. Warriors Circle
      'warriors_circle': 'LINGIN SA MGA MANDIRIGMA',
      'search_members': 'Pangitaa ang mga miyembro...',
      'invite_kin': 'IMBITAHA ANG KALIWAT',
      'warrior_label': 'MANDIRIGMA',
      'duel_btn': 'DUEL',

      // 14. Community Feed
      'living_feed': 'BUHI NGA FEED',
      'community_quiet': 'Hilom ang komunidad... sa pagkakaron. 🌿',
      'comments_label': 'Mga Komento',
      'conversation_soon': 'Sugdan na ang istorya sa dili madugay... 🌿',
      'add_comment_hint': 'Pagdugang og komento...',
      'sharing_update': 'Gi-share ang update ni {name}...',

      // 15. Ancestral Vault Shop
      'ancestral_vault_caps': 'VAULT SA MGA KATIGULANGAN',
      'vault_sealed': 'Nakasira pa ang vault karon.\nBalik lang human sa imong sunod nga ritwal.',
      'ancestral_blessing': 'Panalangin sa mga katigulangan',
      'unlock_caps': 'I-UNLOCK',
      'not_enough_crystals_exchange': 'Nagkinahanglan ka og dugang Mist Crystals para niini nga exchange.',
      'sacred_exchange': 'Sagradong Exchange',
      'owned_caps': 'NAKUHA NA',
      'exchange_confirm': 'Gusto ba nimo mogasto og {cost} Mist Crystals para ma-unlock ang {item}?',
      'processing': 'Gina-proseso...',
      'legacy_unlocked': 'NA-UNLOCK NA ANG KABILIN',
      'tap_return_vault': 'Pinduta para mubalik sa vault',



      // 17. Streak History
      'streak_journey': 'PANAW SA STREAK',
      'on_fire': 'Nag-dilaab ka!',
      'start_journey_today': 'Sugdi ang imong panaw karon!',
      'streak_desc': 'Padayon sa pagkat-on matag adlaw para mudako ang imong streak.',
      'streak_shields': 'MGA SHIELD SA STREAK',
      'available': 'Available',
      'get_more': 'KUHA PA',
      'activity_map': 'MAPA SA AKTIBIDAD',
      'milestones_caps': 'MGA MILESTONE',
      'one_week': 'Usa ka Semana',
      'month_wisdom': 'Bulan sa Kaalam',
      'tribe_guardian_milestone': 'Tigbantay sa Tribo',
      'claim_caps': 'KUHAON',
      'claimed_msg': 'Nakuha na ang {reward}! 🎉',
      'crystals_reward': '{count} ka Crystals',

      // 18. Artifact Detail
      'lore_legend': 'Kaalam ug Alamat',
      'origin_craft': 'Gigikanan ug Likha',
      'share_heritage': 'I-SHARE ANG KABILIN',
      'sharing_lineage': 'Gi-share ang istorya sa kaliwat...',
      'no_legend_yet': 'Wala pay alamat. Pagdiskobre og dugang mga ritwal aron mapadayag ang tibuok istorya niining sagrado nga butang.',

      // 19. Admin Overview
      'village_pulse': 'PULSO SA VILLAGE',
      'platform_stats': 'STATS SA PLATAPORMA',
      'total_users': 'Tanang Users',
      'words_added': 'Mga Pulong nga Gidugang',
      'audio_clips': 'Mga Audio Clip',
      'manage_label': 'DUMALAON',
      'dictionary_label': 'Dictionary',
      'lessons_label': 'Mga Lesson',
      'advanced_analytics': 'ADVANCED PEDAGOGICAL ANALYTICS',
      'system_health_label': 'KAHIMTANG SA SYSTEM',
      'user_growth_label': 'PAGDAGHAN SA USERS (miaging 7 ka adlaw)',
      'gamification_economics': 'GAMIFICATION ug EKONOMIYA',
      'warrior_circle_ops': 'OPS SA WARRIOR CIRCLE',
      'manage_seasons_desc': 'I-manage ang mga season, presyo sa shop, ug duel moderation.',
      'go_economics_hub': 'ADTO SA ECONOMICS HUB',

      'force_rotation': 'PUGSA PAGBALHIN',
      'resume_auto': 'BALIK SA AUTO',
      'pick_manually': 'PILI OG MANWAL',
      'good_morning_name': 'Maayong\nAdlaw,\n{name}!',
      'select_language': 'Pilia ang Pinulongan',
      'english': 'English',
      'filipino': 'Filipino',
      'bisaya': 'Bisaya',

      // 20. System Guide
      'system_nav_guide': 'GIYA SA PAG-NAVIGATE SA SYSTEM',
      'welcome_lumad_lingua': 'Maayong Pag-abot sa Lumad Lingua',
      'guide_title_1': '1. Oryentasyon sa Kultural nga Kabilin',
      'guide_desc_1': 'Usa ka kinatibuk-ang pagtan-aw sa atong katutubong komunidad, nga nagpatin-aw sa kaimportante sa pagpreserba sa atong sagradong mga pinulongan ug tradisyon.',
      'guide_title_2': '2. Roadmap sa Pagkat-on',
      'guide_desc_2': 'Giya sa interactive nga proseso sa pag-uswag. Mouswag pinaagi sa mga tribal units ug scenario hubs.',
      'guide_title_3': '3. Mga Lagda sa Paglitok',
      'guide_desc_3': 'Hibal-i kung giunsa paggamit ang mikropono para sa pag-analisar sa paglitok. Paminaw sa mga katigulangan para makuha ang saktong tono.',
      'guide_title_4': '4. Paggamit sa Dictionary',
      'guide_desc_4': 'Pangita sa atong halapad nga tipiganan sa mga pulong. Susiha ang mga pananglitan ug hubad sa Ingles o Filipino.',
      'guide_title_5': '5. Pakig-uban sa Komunidad',
      'guide_desc_5': 'Sabta ang XP reward cycle, mga ranggo, ug badges. Hagita ang uban sa mga duel ug pagpadala og Tribal Salute.',
      'guide_title_6': '6. Privacy ug Pagmatuod',
      'guide_desc_6': 'Katin-awan sa pagdumala sa komunidad. Hibal-i kung giunsa pagpanalipod ug pagmatuod sa mga katigulangan ang mga natala nga data.',

      // 21. Onboarding Narrative
      'onboarding_title_1': 'Ang mga Lanog naga-Kahanaw',
      'onboarding_sub_1': 'ANG ATONG KARAANG MGA TINGOG',
      'onboarding_desc_1': 'Ang mga sagradong pinulongan sa atong mga tribo naga-kahanaw na daw gabon sa kabuntagon. Gipili ka aron pundokon ang mga nahibilin nga lanog.',
      'onboarding_title_2': 'Ang Ancestral Vault',
      'onboarding_sub_2': 'SAGRADONG KAALAM',
      'onboarding_desc_2': 'Matag pulong nga imong makat-onan mobalik og tipik sa atong kasaysayan. I-unlock ang karaan nga mga artifact ug tukura pag-usab ang kabilin.',
      'onboarding_title_3': 'Imong Panaw sa Tribo',
      'onboarding_sub_3': 'NAGHULAT ANG KAALAM',
      'onboarding_desc_3': 'Apil sa Warriors\' Circle ug pakigtigi sa mga duel. Taas ang dalan sa pagka-hanas, apan ang mga katigulangan nag-uban kanimo.',
      'begin_ritual': 'SUGDI ANG RITWAL',
      'reset_in': 'MAG-RE-RESET SA SULOD SA {time}',
      'challenge_hub': 'SENTRO SA MGA HAGIT',
      'current_lesson': 'KASAMTANGANG LESSON',
      'lesson_progress': 'Progreso sa Lesson',
      'review_ascent': 'BALIKA ANG PAGSAKA',
      'continue_ascent': 'PADAYON SA PAGSAKA',
      'start_your_journey': 'Sugdi ang Imong Panaw',
      'begin_ascent_desc': 'Sugdi ang imong pagsaka sa kabukiran ug diskobreha ang kabilin nga Lumad.',
      'start_unit_1': 'SUGDI ANG UNIT 1',
      'botanical_archivists': 'Ang pinaka-aktibong botanical archivists sa season.',
      'view_all': 'TAN-AWA TANAN',
      'quiet_mountains': 'Hilom nga Kabukiran',
      'no_climbers': 'Wala pay mosaka! Maoy una sa pagsugod sa pagsaka.',
      'archive_xp': 'ARCHIVE XP',
      'keep_flame_alive': 'Pabilin nga buhi ang kalayo!',
      'ritual_empty_desc': 'Walay ritwal karon. Balik lang unya para sa dugang mga hagit!',
    },
  };

  String translate(String key, {Map<String, String>? params}) {
    String value = _localizedValues[languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
    if (params != null) {
      params.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }
    return value;
  }

  String getAuthErrorMessage(dynamic error) {
    if (error is FirebaseAuthException) {
      switch (error.code) {
        case 'user-not-found':
          return translate('error_user_not_found');
        case 'wrong-password':
          return translate('error_wrong_password');
        case 'invalid-credential':
        case 'invalid-login-credentials':
          return translate('error_invalid_credential');
        case 'email-already-in-use':
          return translate('error_email_already_in_use');
        case 'invalid-email':
          return translate('error_invalid_email');
        case 'user-disabled':
          return translate('error_user_disabled');
        case 'too-many-requests':
          return translate('error_too_many_requests');
        case 'network-request-failed':
          return translate('error_network_failed');
        case 'weak-password':
          return translate('error_weak_password');
        case 'operation-not-allowed':
          return translate('error_operation_not_allowed');
        default:
          if (error.message != null && error.message!.isNotEmpty) {
            return error.message!;
          }
          return translate('error_auth_generic');
      }
    }

    if (error is Exception) {
      final msg = error.toString().replaceAll('Exception: ', '');
      if (msg.contains('network-request-failed') || msg.contains('network_error')) {
        return translate('error_network_failed');
      }
      return msg.isEmpty ? translate('error_auth_generic') : msg;
    }

    final message = error.toString();
    return message.isEmpty ? translate('error_auth_generic') : message;
  }
}

final localizationProvider = Provider<AppLocalization>((ref) {
  final prefs = ref.watch(userPreferencesProvider);
  return AppLocalization(prefs.appLanguage);
});
